### PR TITLE
feat: add MPL-404 instructions

### PR DESCRIPTION
**Pull request by qapquiz**
# instructions
  - init_escrow
  - init_nft_data
  - update_escrow
  - update_new_data
  - capture
  - release
  
 This pull request was created for https://app.gib.work/bounties/aeb1c1a9-9af0-4265-9501-8c9e469afd0b in an attempt to solve a bounty #152 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by enzotar** [comment]
Nice. Can you add the remaining instructions and tests. Here's an example command with a test:
https://github.com/space-operator/flow-backend/blob/cce3b951fec14c5d71fa62819786d82881d9f720/crates/cmds-solana/src/transfer_sol.rs#L70

**Comment by qapquiz** [comment]
@enzotar Do you have a proper way to setup token and nft collection for testing purpose?

**Comment by enzotar** [comment]
> @enzotar Do you have a proper way to setup token and nft collection for testing purpose?

Here you go, try these https://github.com/space-operator/flow-backend/pull/163

**Comment by enzotar** [comment]
You can import the jsons into Space Operator to edit the flows.
image
image

**Comment by qapquiz** [comment]
@enzotar Could you take a look at this first? Is it okay for you?

https://github.com/space-operator/flow-backend/blob/477a6ea347a1f105f04d2c51d8cbefc82e678dda/crates/cmds-solana/src/mpl_404/init_escrow.rs#L109-L253

**Comment by enzotar** [comment]
> @enzotar Could you take a look at this first? Is it okay for you?
> 
> https://github.com/space-operator/flow-backend/blob/477a6ea347a1f105f04d2c51d8cbefc82e678dda/crates/cmds-solana/src/mpl_404/init_escrow.rs#L109-L253

Looks good

**Comment by qapquiz** [comment]
@enzotar Done for all of the v1 instructions ❤️

**Review by enzotar — APPROVED** [review]

**Pull request merged**
